---
title: "2021_Week_4_Kenyan_Census_Final_Plot"
author: "MAJ Daniel Baller"
date: "1/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
library(tidyverse)
library(rKenyaCensus)
library(sf)
library(raster)
library(broom)
library(patchwork)
library(scales)
library(extrafont)
```

```{r reading in data}
crops <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-19/crops.csv')
```

```{r setting up the data}
#puling in shape file and adding crops data
shape = KenyaCounties_SHP

#adding a common column to join
crops = crops %>% mutate(County = SubCounty) 

#tidying the data
shape_tidy <- tidy(shape)

#adding crops data
shape$id <- row.names(shape)
shape_tidy <- left_join(shape_tidy, shape@data)
shape_tidy <- left_join(shape_tidy, crops)
```

```{r loading fonts}
# Loading fonts
font_import("C:/Users/daniel.baller/AppData/Local/Microsoft/Windows/Fonts")
loadfonts()
loadfonts(device = "win")
fonts()
```

```{r creating the individual plots}
#Kenyan Coffee Map
a = ggplot(shape_tidy, aes(x = long, y = lat, group = group, fill = Coffee)) +
  geom_polygon(color = "black", size = 0.1) +
  coord_equal() +
  theme_void() +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white", 
                       #breaks = c(20000, 30000, 40000, 50000, 60000),
                       label = comma)+
  labs(fill = "Coffee Farmers")+
  theme(legend.text=element_text(size=14, family = "Kenyan Coffee Rg"),
        legend.title=element_text(size=14, family = "Kenyan Coffee Rg"))

#Kenyan Tea Map
b = ggplot(shape_tidy, aes(x = long, y = lat, group = group, fill = Tea)) +
  geom_polygon(color = "black", size = 0.1) +
  coord_equal() +
  theme_void() +
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white", label = comma)+
  labs(fill = "Tea Farmers")+
  theme(legend.text=element_text(size=14, family = "Kenyan Coffee Rg"),
        legend.title=element_text(size=14, family = "Kenyan Coffee Rg"))
  
#Kenyan Coffee Bar Plot
c = crops %>% 
  filter(County != "KENYA") %>%
  filter(Coffee>0) %>% 
  mutate(County = reorder(County, Coffee)) %>% 
  top_n(13, Coffee) %>% 
  ggplot(aes(y = County, x = Coffee, fill = Coffee))+
  geom_col()+
  labs(x = "Population growing coffee", y = NULL, 
       title = "Top countys with coffee farmers",
       fill = "Coffee Farmers")+
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white", label = comma)+
  scale_x_continuous(label = comma)+
  theme_classic()+
  theme(legend.text=element_text(size=14, family = "Kenyan Coffee Rg"), 
        legend.title=element_text(size=14, family = "Kenyan Coffee Rg"),
        axis.text = element_text(size=14, family = "Kenyan Coffee Rg"), 
        axis.title = element_text(size=14, family = "Kenyan Coffee Rg"),
        plot.title = element_text(size=16, hjust = 0.5, family = "Kenyan Coffee Rg"))

#Kenyan Tea Bar Plot
d = crops %>% 
  filter(County != "KENYA") %>%
  filter(Tea>0) %>% 
  mutate(County = reorder(County, Tea)) %>% 
  top_n(13, Tea) %>% 
  ggplot(aes(y = County, x = Tea, fill = Tea))+
  geom_col()+
  labs(x = "Population growing Tea", y = NULL, 
       title = "Top countys with tea farmers",
       fill = "Tea Farmers")+
  scale_fill_continuous(low="thistle2", high="darkred", 
                       guide="colorbar",na.value="white", label = comma)+
  scale_x_continuous(label = comma)+
  theme_classic()+
  theme(legend.text=element_text(size=14, family = "Kenyan Coffee Rg"), 
        legend.title=element_text(size=14, family = "Kenyan Coffee Rg"),
        axis.text = element_text(size=14, family = "Kenyan Coffee Rg"), 
        axis.title = element_text(size=14, family = "Kenyan Coffee Rg"),
        plot.title = element_text(size=16, hjust = 0.5, family = "Kenyan Coffee Rg"))
```

```{r using patchwork to combine individual plots}
ac = a/c 
bd = b/d
acbd = ac|bd 

final_plot = acbd + plot_annotation(theme = theme(plot.title = element_text(hjust = 0.5, size = 36, family = "Kenyan Coffee Rg"), plot.subtitle = element_text(hjust = 0.5, size = 24, family = "Kenyan Coffee Rg"), text = element_text(family = "Kenyan Coffee Rg")), title = "Who's Growing Kenyan Coffee and Tea?",subtitle = "Murang'a tops the list for coffee farmers, while Kisii has the most tea farmers.", caption = "Tidy Tuesday 2021 Week 4 | Graphic: @danielpballer | Data: rKenyaCensus")
```

```{r saving final plot}
ggsave("2021_Week_4_Kenyan_Census.png", plot = final_plot, scale = 3)
```

