---
title: "2021_Week_10_Superbowl_Ads_Final_Plot"
author: "MAJ Daniel Baller"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
library(tidyverse)
library(ggalluvial)
library(igraph)
library(colormap)
library(ggraph)
library(ggtext)
library(extrafont)
library(RColorBrewer)
library(colorspace)
```

```{r reading in data}
youtube <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-02/youtube.csv')
```

```{r loading fonts}
font_import("C:/Users/daniel.baller/AppData/Local/Microsoft/Windows/Fonts")
loadfonts()
loadfonts(device = "win")
fonts()
```

```{r final plot}
final_plot = youtube %>% 
  select(year, brand, funny, show_product_quickly, patriotic, celebrity, danger, animals, use_sex) %>% 
  pivot_longer(cols = c(3:9), names_to = "Category", values_to = "YES") %>% filter(YES==TRUE) %>% 
  mutate(Category = case_when(Category == "use_sex"~"use sex",
                              TRUE~Category)) %>% 
  mutate(brand = fct_infreq(brand)) %>% 
  group_by(brand, Category) %>% count() %>% 
  filter(Category!="show_product_quickly") %>% 
  ggplot(aes(axis1 = brand, axis2 = Category, y = n)) +
  scale_x_discrete(limits = c("Brand", "Category"), expand = c(.2, .05)) +
  #xlab("") +
  geom_alluvium(aes(fill = brand)) +
  scale_fill_brewer(palette = "Paired")+
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), family = "Freshman", size = 4) +
  theme_minimal() +
  ggtitle("Top Ten Super Bowl Advertisers",
          "How do they design their adds?") +
  labs(caption = "Tidy Tuesday 2021, Week 10 | Graphic: @danielpballer | Data:FiveThirtyEight") +
  theme_void()+
  theme(plot.title = element_text(hjust = .5, size = 24, family = "Freshman"),
        plot.subtitle = element_text(hjust = .5,size = 16, family = "Freshman"),
        plot.caption = element_text(size = 10),
        legend.position = "None")

final_plot
```

```{r saving the plot}
ggsave(filename = "2021_Week_10_Super_Bowl_Ads.png", plot = final_plot, device = "png", dpi = "retina")
```

