---
title: "Week_38_Gov_Spending_on_Kids_Final_Plot"
author: "MAJ Daniel Baller"
date: "9/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r loading packages}
library(tidyverse)
library(png)
library(cowplot)
library(usmap)
library(ggdark)
library(extrafont)
library(RColorBrewer)
```

```{r reading in data}
kids <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-15/kids.csv')
```

Loading fonts
```{r}
font_import("C:/Users/daniel.baller/AppData/Local/Microsoft/Windows/Fonts")
loadfonts(device = "win")
fonts()
```

Final Plot
```{r}
#Loading in the background image
image <- readPNG("blackboard.PNG")

#Creating the Final Plot
a = plot_usmap(regions = "states", 
           data = kids %>% filter(variable=="highered") %>% filter(year == 2016),
           values = "inf_adj_perchild", color = "black") + 
  scale_fill_distiller(palette = "RdYlGn", direction = 1, name = "Public spending \nin $1,000s per child")+
  labs(title = "US Public Spending on Higher Education by State",
       subtitle = "Wyoming is the highest at $4.04K per child while Washington DC is the lowest at $0.806K per child",
       caption = "Tidy Tuesday Week 38 | Graphic: @danielpballer | Data: Urban Institute")+
  theme_void()+
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, size = 36, 
                                  family = "whatever it takes", face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 18, 
                                     family = "whatever it takes", face = "bold"), 
        text = element_text(family = "whatever it takes", face = "bold", 
                            color = "#fafae0"),
        legend.text  = element_text(size = 14),
        plot.caption = element_text(size = 16))

#adding the plot to the background image
ggdraw()+
  draw_image(image, scale = 1.5)+
  draw_plot(a)
```

