---
title: "Tidy-Tuesday-Astronauts"
author: "MAJ Daniel Baller"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

Loading Packages
```{r}
library(tidyverse)
library(gganimate)
library(treemapify)
library(hrbrthemes)
library(ggthemes)
library(ggthemr)
library(mdthemes)
library(ggdark)
```

Reading in Data
```{r}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
```

Saving Data
```{r}
write_csv(astronauts, "week29_astronauts.csv")
```

Some basic numbers and animation over the years of how many astronauts per country
```{r}
#How many entries for each country
astronauts %>% 
  count(nationality) %>% arrange(desc(n))

#How many missions for each astronaut
astronauts %>% count(name) %>% arrange(desc(n))

astronauts %>% 
#  mutate(nationality = fct_reorder(nationality, count(nationality), .desc = T)) %>% 
  ggplot(aes(y = nationality))+
  geom_bar(stat = "count")+
  labs(title = 'Year: {frame_time}', x = 'Count', y = 'Country') +
  transition_time(year_of_mission) +
  ease_aes('linear')


# astronauts %>% 
#   ggplot(aes(
#     label = nationality,
#     area = count(nationality),
#   )) +
#   geom_treemap(layout = "fixed") +
#   geom_treemap_text(layout = "fixed", place = "centre", grow = TRUE, colour = "white") +
#   geom_treemap_subgroup_text(layout = "fixed", place = "centre") +
#   geom_treemap_subgroup_border(layout = "fixed") +
#   transition_time(year) +
#   ease_aes('linear') +
#   labs(title = "Year: {frame_time}")
```

Playing around with the animation
```{r}
astronauts %>% 
  group_by(nationality, year_of_mission) %>% 
  mutate(total = max(nationwide_number)-min(nationwide_number)) %>% 
  ggplot(aes(y = nationality))+
  geom_bar(stat = "count")+
  labs(title = 'Year: {frame_time}', x = 'Count', y = 'Country') +
  transition_time(year_of_mission) +
  ease_aes('linear')


astronauts %>% 
  ggplot(aes(y = nationality))+
  geom_bar(stat = max(nationwide_number))+
  labs(title = 'Year: {frame_time}', x = 'Count', y = 'Country') +
  transition_time(year_of_mission) +
  ease_aes('linear')

  transition_states(year_of_mission,
                    transition_length = 2)
```

```{r}
astronauts %>% 
  ggplot()+geom_col(aes(y = mission_title, x = hours_mission, fill = nationality))+coord_polar(start = 270, direction = 1, clip = "on")

```

Stats on the U.S. and U.S.S.R./Russia
```{r}
#Number above and below the average
astronauts %>% 
  filter(nationality =="U.S." | nationality == "U.S.S.R/Russia") %>% 
  group_by(nationality) %>% 
  group_by(name) %>% 
  filter(mission_number == max(mission_number)) %>% 
  ungroup() %>% 
  #count(nationality) %>% 
  mutate(Above = ifelse(total_hrs_sum - mean(total_hrs_sum) > 0, "Longer than average", "Shorter than average")) %>% 
  count(nationality, Above)

#Total mission hours per country  
astronauts %>% 
  filter(nationality =="U.S." | nationality == "U.S.S.R/Russia") %>% 
  group_by(nationality) %>% 
  group_by(name) %>% 
  filter(mission_number == max(mission_number)) %>% 
  ungroup() %>% 
  #count(nationality) %>% 
  mutate(Above = ifelse(total_hrs_sum - mean(total_hrs_sum) > 0, "Longer than average", "Shorter than average")) %>% 
  group_by(nationality) %>% 
  summarize(total = sum(total_hrs_sum))
summ

#total astronouts 
#   nationality        n
#   <chr>          <int>
# 1 U.S.             334
# 2 U.S.S.R/Russia   122

#   nationality    Above                    n
#   <chr>          <chr>                <int>
# 1 U.S.           Longer than average     62
# 2 U.S.           Shorter than average   282
# 3 U.S.S.R/Russia Longer than average     74
# 4 U.S.S.R/Russia Shorter than average    48

#   nationality      total
#   <chr>            <dbl>
# 1 U.S.           500683.
# 2 U.S.S.R/Russia 685908.

#calculating mean and median of total hours
astronauts %>% summarise(mean(total_hrs_sum), median(total_hrs_sum))
```

First version of final plot
```{r}
ast = astronauts %>% 
  filter(nationality =="U.S." | nationality == "U.S.S.R/Russia") %>% 
  mutate(nationality = if_else(nationality =="U.S.S.R/Russia", "U.S.S.R./Russia", nationality)) %>% 
  mutate(name = as.factor(name)) %>% 
  mutate(name = fct_reorder(name, total_hrs_sum, .fun = 'max')) %>% 
  mutate(Above = ifelse(total_hrs_sum - mean(total_hrs_sum) > 0, "Longer than average", "Shorter than average")) %>% 
  ggplot(aes(x = total_hrs_sum, y = name, color = Above)) +
        geom_segment(aes(x = 2968, y = name, xend = total_hrs_sum, yend = name), color = "grey50", size = .3) + 
        geom_point(size = .8)+
  scale_color_manual(values = c("green", "red"))+
        facet_wrap(~nationality)+
  #geom_line(x = 932, color = "red")+
  labs(y = "Name", x = "Total Mission Hours in Space", color = NULL, title = "Comparing U.S. and U.S.S.R./Russian Astronaut's Time in Space", subtitle = "62 of the U.S.'s 334 astronauts (18.5%) and 74 of the U.S.S.R./Russia's 122 astronauts (60.7%) have exceeded the avererage total mission hours in space of all astronauts (2968 hours). \nAstronauts from the U.S.S.R./Russia have spent a total of 685,908 hours in space compared to 500,638 total hours for U.S. astronauts", caption = "@danielpballer")+
  dark_theme_bw()+
  #dark_theme_void()+
  theme(axis.text.y = element_text(size = 1), plot.title = element_text(size = 26), axis.ticks = element_blank())

ggsave(filename="gg-higher-res.png", plot=ast, device="png", height=8.5, width=14, units="in", dpi=800)
```

Final Plot
```{r}
ast2 = astronauts %>% 
  filter(nationality =="U.S." | nationality == "U.S.S.R/Russia") %>% 
  mutate(nationality = if_else(nationality =="U.S.", "United States", nationality)) %>% 
  mutate(nationality = if_else(nationality =="U.S.S.R/Russia", "U.S.S.R./Russia", nationality)) %>%
  mutate(nationality = factor(nationality, levels = c("United States","U.S.S.R./Russia"))) %>%
 # mutate(nationality = fct_reorder(nationality, levels = c("United States","U.S.S.R./Russia"))) %>% 
  mutate(name = as.factor(name)) %>% 
  mutate(name = fct_reorder(name, total_hrs_sum, .fun = 'max')) %>% 
  mutate(Above = ifelse(total_hrs_sum - mean(total_hrs_sum) > 0, "Longer than average", "Shorter than average")) %>% 
  ggplot(aes(x = total_hrs_sum, y = name, color = Above)) +
        geom_segment(aes(x = 2968, y = name, xend = total_hrs_sum, yend = name), color = "grey50", size = .3) + 
        geom_point(size = .8)+
  scale_color_manual(values = c("green", "red"))+
        facet_wrap(~nationality)+
  #geom_line(x = 932, color = "red")+
  labs(y = "Name", x = "Total Mission Hours in Space", color = NULL, title = "Comparing United States and U.S.S.R./Russian Astronaut's Time in Space", subtitle = "62 of the United States' 334 astronauts (18.5%) and 74 of the U.S.S.R./Russia's 122 astronauts (60.7%) have exceeded the avererage total mission \nhours in space of all astronauts (2,968 hours). Astronauts from the U.S.S.R./Russia have spent a total of 685,908 hours in space compared to \n500,638 total hours for United States astronauts.", caption = "Graphic: @danielpballer | Data: Mariya Stavnichuk and Tatsuya Corlett")+
  dark_theme_bw()+
  #dark_theme_void()+
  theme(axis.text.y = element_text(size = 1), plot.title = element_text(size = 22), axis.ticks = element_blank())

#Saving as high res image
ggsave(filename="Week28 Astronauts.png", plot=ast2, device="png", height=8.5, width=11, units="in", dpi=800)
ggsave(filename="gg-higher-res3.png", plot=ast2, device="png", height=1700, width=2200, units="pixels", dpi=800)
```

