---
title: "Week_34_Plants_Exploration"
author: "MAJ Daniel Baller"
date: "8/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r loading packages}
library(tidyverse)
library(ggmosaic)
library(geofacet)
library(cowplot)
library(patchwork)
library(ggalluvial)
library(ggdark)
library(ggpomological)
library(showtext)
library(extrafont)
```

```{r reading in data}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')
```

```{r saving data}
write_csv(plants, "Week_34_Plants.csv")
write_csv(actions, "Week_34_Actions.csv")
write_csv(threats, "Week_34_Threats.csv")
```

Playing around with some mosaic plots for each continent faceted by country
```{r}
#top countries with extinct plants
plants %>% count(country) %>% 
  arrange(desc(n))

threats %>% 
  filter(continent=="Oceania") %>% 
  group_by(country) %>% count(threat_type, threatened) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()

threats %>% 
  filter(continent=="North America") %>% 
  group_by(country) %>% count(threat_type, threatened) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()

threats %>% 
  filter(continent=="South America") %>% 
  group_by(country) %>% count(threat_type, threatened) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()

threats %>% 
  filter(continent=="Europe") %>% 
  group_by(country) %>% count(threat_type, threatened) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()

threats %>% 
  filter(continent=="Asia") %>% 
  group_by(country) %>% count(threat_type, threatened) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()
```

Trying out some assubiul plots
```{r}
threats %>% 
  filter(threatened == 1) %>% 
  count(continent, group, threat_type,red_list_category) %>% 
  ggplot(aes(axis1 = continent, axis2 = group, axis3 = threat_type,
           y = n)) +
  scale_x_discrete(limits = c("Country", "Group", "Threat Type"), expand = c(.2, .05)) +
  #xlab("Demographic") +
  geom_alluvium(aes(fill = red_list_category)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal() +
  ggtitle("1st alluviul plot",
          "")

threats %>% 
  filter(threatened == 1) %>% 
  count(continent, country, group, threat_type,red_list_category) %>% 
  ggplot(aes(axis1 = continent, axis2 = threat_type, axis3 = red_list_category,
           y = n)) +
  scale_x_discrete(limits = c("Country", "Group", "Threat Type"), expand = c(.2, .05)) +
  #xlab("Demographic") +
  geom_alluvium(aes(fill = group)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal() +
  ggtitle("2nd alluviul plot",
          "")
```

Mosaic plot for the US
```{r}
threats %>% 
  filter(country == "United States") %>% 
  filter(threatened==1) %>%
  count(threat_type, threatened) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type,n), fill = threat_type)) +
  #facet_wrap(~ country)+
  labs(x = NULL, y = NULL)+
  theme_void()
```

Mosaic and bar plot for the US over time
```{r}
threats %>% 
  filter(continent=="North America") %>% 
  filter(threat_type!="Unknown") %>% 
  group_by(country) %>% count(threat_type, threatened, year_last_seen) %>% 
  filter(threatened==1) %>% 
  ggplot()+
  geom_mosaic(aes(x = product(threat_type), fill = threat_type)) +
  facet_wrap(~year_last_seen)+
  labs(x = NULL, y = NULL)+
  scale_fill_pomological()+
  theme_pomological_fancy()

threats %>% 
  filter(continent=="North America") %>% 
  filter(threat_type!="Unknown") %>% 
  group_by(country) %>% count(threat_type, threatened, year_last_seen) %>%
  filter(threatened==1) %>% 
  ggplot(aes(x = threat_type, y = n, fill = threat_type))+
  geom_bar(stat = "identity") +
  facet_wrap(~year_last_seen)+
  labs(x = NULL, y = NULL)+
  scale_fill_pomological()+
  theme_pomological_fancy()
```

Loading fonts and creating the final plot
```{r}
# Loading fonts
font_import()
loadfonts(device = "win")
fonts()

# Final Plot
threats %>% 
  mutate(year_last_seen = factor(year_last_seen, levels = c("2000-2020","1980-1999","1960-1979","1940-1959","1920 - 1939","1900-1919","Before 1900"))) %>% 
  mutate(continent = factor(continent, levels = c("Africa","Asia","Oceania","North America","South America","Europe"))) %>% 
  filter(year_last_seen!="NA") %>% 
  group_by(year_last_seen, continent) %>% 
  count(continent, threat_type, threatened, year_last_seen) %>% 
  filter(threatened==1) %>% 
  ggplot(aes(x = year_last_seen, y = n, fill = threat_type))+
  geom_bar(stat = "identity", position = "fill")+
 facet_wrap(~continent)+
  labs(x = NULL, y = NULL, fill = "Type of Threat", 
       title = "What's Threatening Our Plants?",
       subtitle = "Known threats to plants that were last seen in each 20 year block", 
       caption = "Graphic: @danielpballer | Data: (IUCN) Red list of Threatened Species")+
  scale_fill_manual(values = c("#c03728", "#919c4c", "#fd8f24", "#f5c04a", "#e68c7c", "#828585", "#c3c377", "#4f5157", "#6f5438", "#a89985", "#efe1c6","#f8eed1"))+
  scale_y_continuous(breaks = NULL) +
  coord_flip()+
  theme_pomological(axis.text.size = 10)+
  theme()+
  theme(plot.title = element_text(hjust = 0.5, size = 26),
        plot.subtitle = element_text(hjust = .5, size = 18),
        text = element_text(family = "Sylfaen", size = 10),
        legend.text = element_text(size = 14),
        strip.text.x = element_text(size = 14),
        legend.title = element_text(size = 16),
        plot.margin=unit(c(.5,1.5,.5,1),"cm"))
```
