---
title: "X-men"
author: "MAJ Daniel Baller"
date: "6/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

Loading packages
```{r}
library(tidyverse)
library(ggthemes)
library(yarrr)
library(patchwork)
library(gghighlight)
```

Reading in Data
```{r}
comic_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/comic_bechdel.csv')

character_visualization <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/character_visualization.csv')

characters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/characters.csv')

xmen_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/xmen_bechdel.csv')

covers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/covers.csv')

issue_collaborators <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/issue_collaborators.csv')

locations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-30/locations.csv')
```

Saving Data
```{r}
write_csv(comic_bechdel, "week27_comic_bechdel.csv")
write_csv(character_visualization, "week27_character_visualization.csv")
write_csv(characters, "week27_characters.csv")
write_csv(xmen_bechdel, "week27_xmen_bechdel.csv")
write_csv(covers, "week27_covers.csv")
write_csv(issue_collaborators, "week27_issue_collaborators.csv")
write_csv(locations, "week27_locations.csv")
```

Modifying Character names and calculating totals for each character.
```{r}
character_visualization %>% 
  mutate(character = if_else(str_detect(character,"=")==T, sub(" =.*", "", character),character)) %>% 
  mutate(character = if_else(str_detect(character,"\\(")==T, sub(" \\(.*", "", character),character))
  count(character)

#Calculating total numbers for each character
char_grouped  = character_visualization %>% 
  mutate(character = if_else(str_detect(character,"=")==T, sub(" =.*", "", character),character)) %>% 
  mutate(character = if_else(str_detect(character,"\\(")==T, sub(" \\(.*", "", character),character)) %>% 
  mutate(character = if_else(str_detect(character,"\\(")==T, sub("\\(.*", "", character),character)) %>% 
  group_by(character) %>% 
  summarise(Speech = sum(speech),Thought = sum(thought), Narrative = sum(narrative), 
            Depicted = sum(depicted))
```

Creating Final Plot
```{r}
xmen = piratepal(palette = "xmen")
a = char_grouped %>%
  pivot_longer(-character, names_to = "what", values_to = "count") %>% 
  ggplot(aes(fill = what, y = count, x = character))+ 
  geom_bar(position="stack", stat="identity")+ coord_flip()+
  scale_fill_manual(values = c("#026CCBFF", "#F51E02FF", "#05B102FF", "#FB9F53FF"))+
  labs(x = "Character", y = "Count", title = "By Count", fill = "")+
  theme_classic()+
  theme(legend.position = "none")

b = char_grouped %>%
  pivot_longer(-character, names_to = "what", values_to = "count") %>% 
  ggplot(aes(fill = what, y = count, x = character))+  #, alpha = .99
  geom_bar(position="fill", stat="identity")+ coord_flip()+
  scale_fill_manual(values = c("#026CCBFF", "#F51E02FF", "#05B102FF", "#FB9F53FF"))+
  labs(x = NULL, y = "Percent", title = "By Percentage", fill = "")+
  theme_classic()
  
a+b+plot_annotation(title = "How Characters Appear in the Claremont Run", theme = theme(plot.title = element_text(hjust = 0.5, size = 24), plot.subtitle = element_text(hjust = 0.5, size = 16)), subtitle = "Comparing total observations to percentages", caption = "@danielpballer")
```

Looking at speech, thought, and narration over the issues highlighting wolverine
```{r}
s = character_visualization %>% 
  ggplot()+geom_line(aes(x = issue, y = speech, color = character))
  
sh = s+gghighlight(character == "Wolverine = Logan")

t = character_visualization %>% 
  ggplot()+geom_line(aes(x = issue, y = thought, color = character))
  
th = t+gghighlight(character == "Wolverine = Logan")


n = character_visualization %>% 
  ggplot()+geom_line(aes(x = issue, y = narrative, color = character))
  
nh = n+gghighlight(character == "Wolverine = Logan")

sh/th/nh
```

Does killing make you hungry: comparing how much characters are shown eating vs how much they kill.
```{r}
food = characters %>%  
  filter(depicted_eating_food>0) %>% 
  select(character, depicted_eating_food) %>% 
  group_by(character) %>% 
  summarise(eat = sum(depicted_eating_food)) %>% 
  arrange(desc(eat)) 

kills_human = characters %>%  
  filter(number_of_kills_humans>0 | number_of_kills_non_humans>0 & number_of_kills_non_humans< 1000000) %>% 
  select(issue, character, number_of_kills_humans, number_of_kills_non_humans) %>%
  mutate(tot_kills = number_of_kills_non_humans+number_of_kills_humans) %>% 
  group_by(character) %>% 
  summarise(kills = sum(tot_kills)) %>% 
  arrange(desc(kills))

tot = food %>% inner_join(kills_human)  
  
tot %>% 
  ggplot(aes(x = eat, y = kills))+geom_point()+geom_text(aes(label = character, overlap = F))#+geom_smooth(method = "lm")
```

